//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50215.44
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "BlackJack.Properties.Resources.get_ResourceManager():System.Resources.ResourceMan" +
    "ager")]
[assembly: global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "BlackJack.Properties.Resources.get_Culture():System.Globalization.CultureInfo")]
[assembly: global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "BlackJack.Properties.Resources.set_Culture(System.Globalization.CultureInfo):Void" +
    "")]

namespace BlackJack.Properties
{


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if ((resourceMan == null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BlackJack.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        internal static System.Drawing.Bitmap backGreen
        {
            get
            {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("backGreen", resourceCulture)));
            }
        }

        internal static System.Drawing.Bitmap Background
        {
            get
            {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("Background", resourceCulture)));
            }
        }

        internal static System.Drawing.Bitmap BorderPlaceYourBetBottom
        {
            get
            {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("BorderPlaceYourBetBottom", resourceCulture)));
            }
        }

        internal static System.Drawing.Bitmap BorderPlaceYourBetTop
        {
            get
            {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("BorderPlaceYourBetTop", resourceCulture)));
            }
        }

        internal static System.Drawing.Bitmap ButtonRound
        {
            get
            {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("ButtonRound", resourceCulture)));
            }
        }

        internal static System.Drawing.Bitmap ButtonRoundRollOver
        {
            get
            {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("ButtonRoundRollOver", resourceCulture)));
            }
        }

        internal static System.Drawing.Bitmap ButtonSquare
        {
            get
            {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("ButtonSquare", resourceCulture)));
            }
        }

        internal static System.Drawing.Bitmap cardSkin
        {
            get
            {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("cardSkin", resourceCulture)));
            }
        }

        internal static System.Drawing.Bitmap coin1
        {
            get
            {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("coin1", resourceCulture)));
            }
        }

        internal static System.Drawing.Bitmap coin2
        {
            get
            {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("coin2", resourceCulture)));
            }
        }

        internal static System.Drawing.Bitmap coin3
        {
            get
            {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("coin3", resourceCulture)));
            }
        }

        internal static System.Drawing.Bitmap coin4
        {
            get
            {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("coin4", resourceCulture)));
            }
        }

        internal static System.Drawing.Bitmap FrameBlue
        {
            get
            {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("FrameBlue", resourceCulture)));
            }
        }

        internal static System.Drawing.Bitmap FrameBrightRed
        {
            get
            {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("FrameBrightRed", resourceCulture)));
            }
        }

        internal static System.Drawing.Bitmap FrameOrange
        {
            get
            {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("FrameOrange", resourceCulture)));
            }
        }

        internal static System.Drawing.Bitmap FramePink
        {
            get
            {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("FramePink", resourceCulture)));
            }
        }

        internal static System.Drawing.Bitmap FrameRed
        {
            get
            {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("FrameRed", resourceCulture)));
            }
        }

        internal static System.Drawing.Bitmap FrameTextField1
        {
            get
            {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("FrameTextField1", resourceCulture)));
            }
        }

        internal static System.Drawing.Bitmap FrameTextField2
        {
            get
            {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("FrameTextField2", resourceCulture)));
            }
        }

        internal static System.Drawing.Bitmap FrameTextField3
        {
            get
            {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("FrameTextField3", resourceCulture)));
            }
        }

        internal static System.Drawing.Bitmap FrameTextField4
        {
            get
            {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("FrameTextField4", resourceCulture)));
            }
        }

        internal static System.Drawing.Bitmap FrameTextField5
        {
            get
            {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("FrameTextField5", resourceCulture)));
            }
        }

        internal static System.Drawing.Bitmap SplashPage
        {
            get
            {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("SplashPage", resourceCulture)));
            }
        }

        internal static System.Drawing.Bitmap StartMenuIcon
        {
            get
            {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("StartMenuIcon", resourceCulture)));
            }
        }

        internal static System.Drawing.Icon TemplateIcon
        {
            get
            {
                return ((System.Drawing.Icon)(ResourceManager.GetObject("TemplateIcon", resourceCulture)));
            }
        }
    }
}
